name: Release Bunker Version

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: lts/*

    - name: Build Repo
      run: |
        npm i && npm run build
    - uses: actions/upload-artifact@v4
      with:
        name: kolf-build-latest-appImage
        path: dist/index.html
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          dist/index.html
    - name: Push to update branch
      run: |
         git config --global user.name "github-actions[bot]"
         git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
         git add -A
         git checkout -b updates
         git commit dist/index.html
         git status
         git push
