name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3

      - name: Install Dependencies
        run: |
          npm ci

      - name: Build
        run: |
          npm run build

      - name: Push to build branch
        run: |
          git checkout -b build
          git add -f ./dist
          git commit -m "Build"
          git push origin build

      - name: Clean up
        run: |
          git checkout main
